# Generated by Django 2.1.3 on 2018-11-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='chice_text',
            new_name='chioce_text',
        ),
    ]
